[package]
name = 'server'
version = '0.5.0'
authors = ['JADSN <jadsn1894@gmail.com>']
edition = '2018'
[dependencies.rusqlite]
version = '0.23.1'
features = ['bundled']

[dependencies.shared]
path = '../shared'
