[package]
name = 'shared'
version = '0.7.0'
authors = ['JADSN <jadsn1894@gmail.com>']
edition = '2018'

[dependencies]
serde_json = '1.0.57'

[dependencies.serde]
version = '1.0.115'
features = ['derive']
