[package]
name = 'termcli'
version = '0.6.1'
authors = ['JADSN <jadsn1894@gmail.com>']
edition = '2018'

[dependencies]
clap = '2.33.1'
cli-table = '0.3.1'

[dependencies.www]
path = '../www'

[dependencies.server]
path = '../server'

[dependencies.shared]
path = '../shared'
